name: bbb_app
description: BigBlueButton client app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.6+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_spinkit: ^5.1.0
  flutter_webrtc: ^0.8.9
  shared_preferences: ^2.0.15
  shared_preferences_macos: ^2.0.4
  shared_preferences_web: ^2.0.4
  share_plus: ^4.0.10
  http: ^0.13.4
  html: ^0.15.0
  day_night_switcher: ^0.2.0+1
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  intl: ^0.17.0
  sprintf: ^6.0.0
  flutter_svg: ^1.1.0
  sip_ua: #^0.3.5
    git: https://github.com/flutter-webrtc/dart-sip-ua.git
  flutter_markdown: ^0.6.10+2
  uni_links: ^0.5.1
  flutter_foreground_plugin:
    git:
      url: https://github.com/jja08111/flutter_foreground_service_plugin.git
      ref: 8a09c7b0aeb9d31204147fe6ee126c8a52471e3a
  logger: ^1.1.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  url_launcher: ^6.1.3
  get: ^4.6.1
  connectivity_plus: ^1.4.0
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0
  flutter_pw_validator: ^1.4.2
  json_annotation: ^4.5.0
  bottom_bar: ^2.0.1
  awesome_dialog: ^2.2.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/GitHub_Logo.png
    - assets/privacy_policy/de.md
    - assets/privacy_policy/en.md
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserratlight300.ttf
          weight: 300
        - asset: assets/fonts/montserratmedium500.ttf
          weight: 500
        - asset: assets/fonts/montserratbold700.ttf
          weight: 700
        - asset: assets/fonts/montserratregular400.ttf
          weight: 400
        - asset: assets/fonts/montserratsemibold600.ttf
          weight: 600
        - asset: assets/fonts/montserratextralight200.ttf
          weight: 200
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunitolight300.ttf
          weight: 300
        - asset: assets/fonts/nunitoregular400.ttf
          weight: 400
        - asset: assets/fonts/nunitosemibold600.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  image_path_android: "assets/logo.png"
  ios: true
  image_path_ios: "assets/logo.png"

  #"assets/icon/android/icon.png"
  #"assets/icon/ios/icon.png"
